-- Profiles
INSERT INTO profile (name) values ('admin');
INSERT INTO profile (name) values ('editor');
INSERT INTO profile (name) values ('user');

-- Collections
INSERT INTO collection (category, name, short_name) VALUES ('Botanique', 'Cryptogames', 'PC');
INSERT INTO collection (category, name, short_name) VALUES ('Botanique', 'Ethnobotanique', 'PAT');
INSERT INTO collection (category, name, short_name) VALUES ('Botanique', 'Herbier du harmas de J. H. Fabre', 'FABR');
INSERT INTO collection (category, name, short_name) VALUES ('Botanique', 'Jardins', 'JB');
INSERT INTO collection (category, name, short_name) VALUES ('Botanique', 'Laboratoire Maritime de Dinard', 'DIN');
INSERT INTO collection (category, name, short_name) VALUES ('Botanique', 'Plantes vasculaires', 'P');
INSERT INTO collection (category, name, short_name) VALUES ('Botanique', 'Souches Fongiques', 'RF');   
INSERT INTO collection (category, name, short_name) VALUES ('Terre et hommes', 'Anthropologie', 'HA');
INSERT INTO collection (category, name, short_name) VALUES ('Terre et hommes', 'Météorites', 'GT');
INSERT INTO collection (category, name, short_name) VALUES ('Terre et hommes', 'Paléontologie', 'F');
INSERT INTO collection (category, name, short_name) VALUES ('Terre et hommes', 'Préhistoire', 'HP');
INSERT INTO collection (category, name, short_name) VALUES ('Terre et hommes', 'Roches exogènes', 'GG');
INSERT INTO collection (category, name, short_name) VALUES ('Zoologie', 'Annélides, Polychètes et Sipunculides', 'IA');
INSERT INTO collection (category, name, short_name) VALUES ('Zoologie', 'Aptérygotes & Collemboles', 'EA');
INSERT INTO collection (category, name, short_name) VALUES ('Zoologie', 'Arachnides : Araneae', 'AR');
INSERT INTO collection (category, name, short_name) VALUES ('Zoologie', 'Arachnides : Scorpionidae', 'RS');
INSERT INTO collection (category, name, short_name) VALUES ('Zoologie', 'Bryozoaires Brachiopodes', 'IB');
INSERT INTO collection (category, name, short_name) VALUES ('Zoologie', 'Cnidaires', 'IK');
INSERT INTO collection (category, name, short_name) VALUES ('Zoologie', 'Crustacés', 'IU');
INSERT INTO collection (category, name, short_name) VALUES ('Zoologie', 'Échinodermes', 'IE');
INSERT INTO collection (category, name, short_name) VALUES ('Zoologie', 'Insectes : Coléoptères', 'EC');
INSERT INTO collection (category, name, short_name) VALUES ('Zoologie', 'Insectes : Diptères', 'ED');
INSERT INTO collection (category, name, short_name) VALUES ('Zoologie', 'Insectes : Hémiptères', 'EH');
INSERT INTO collection (category, name, short_name) VALUES ('Zoologie', 'Insectes : Hyménoptères', 'EY');
INSERT INTO collection (category, name, short_name) VALUES ('Zoologie', 'Insectes : Lépidoptères', 'EL');
INSERT INTO collection (category, name, short_name) VALUES ('Zoologie', 'Insectes : Orthoptéroïdes', 'EO');
INSERT INTO collection (category, name, short_name) VALUES ('Zoologie', 'Insectes : Petits ordres & Odonates', 'EP');
INSERT INTO collection (category, name, short_name) VALUES ('Zoologie', 'Mollusques', 'IM');
INSERT INTO collection (category, name, short_name) VALUES ('Zoologie', 'Myriapodes', 'MY');
INSERT INTO collection (category, name, short_name) VALUES ('Zoologie', 'Nématodes', 'IN');
INSERT INTO collection (category, name, short_name) VALUES ('Zoologie', 'Porifères', 'IP');
INSERT INTO collection (category, name, short_name) VALUES ('Zoologie', 'Tuniciers/ascidies', 'IT');
INSERT INTO collection (category, name, short_name) VALUES ('Zoologie', 'Vertébrés : Autres', 'ZA');
INSERT INTO collection (category, name, short_name) VALUES ('Zoologie', 'Vertébrés : Ichtyologie', 'IC');
INSERT INTO collection (category, name, short_name) VALUES ('Zoologie', 'Vertébrés : Mammifères', 'ZM');
INSERT INTO collection (category, name, short_name) VALUES ('Zoologie', 'Vertébrés : Oiseaux', 'ZO');
INSERT INTO collection (category, name, short_name) VALUES ('Zoologie', 'Vertébrés : Reptiles & Amphibiens', 'RA');
